AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3]
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 50
CLASSES: 4
WEIGHTS: imagenet
LEARNING_RATE: 0.00001  
DROPOUT_RATE: 0.5

EARLY_STOPPING_PATIENCE: 12
REDUCE_LR_PATIENCE: 6
REDUCE_LR_FACTOR: 0.2
MIN_LR: 0.0000001